### ISSUE TITLE
Consider Skypack CDN

### ISSUE THREAD

**Issue by metafeather** [simonw/download-esm#3]
Skypack (previously Pika) seems well aligned with your needs and may make it simpler to download more packages, especially ones also loading CSS, Icons or WSAM files to function.

> Load optimized npm packages with no install and no build tools
> https://www.skypack.dev/

The pinned URL's feature in particular would reduce the number of files downloaded.

**Comment by simonw** [comment]
I've used and liked Skypack in the past but it's not looking like a healthy project with a guaranteed long-term future any more:

- https://github.com/skypackjs/skypack-cdn/issues/343
- https://github.com/skypackjs/skypack-cdn/issues/329
